// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSubject = "subject"

// Subject mapped from table <subject>
type Subject struct {
	ID          uint32 `gorm:"column:id;type:int(10) unsigned;primaryKey;autoIncrement:true" json:"id"`
	SubjectName string `gorm:"column:subject_name;type:varchar(255);not null" json:"subject_name"`
}

// TableName Subject's table name
func (*Subject) TableName() string {
	return TableNameSubject
}
