// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID         uint32     `gorm:"column:id;type:int(10) unsigned;primaryKey;autoIncrement:true" json:"id"`
	Username   string     `gorm:"column:username;type:varchar(255);not null" json:"username"`
	Label      string     `gorm:"column:label;type:varchar(255);not null" json:"label"`
	ClassID    uint32     `gorm:"column:class_id;type:int(10) unsigned;not null" json:"class_id"`
	StudentID  string     `gorm:"column:student_id;type:varchar(20);not null;uniqueIndex:sid,priority:1" json:"student_id"`
	AddTime    time.Time  `gorm:"column:add_time;type:datetime;not null" json:"add_time"`
	UpdateTime *time.Time `gorm:"column:update_time;type:datetime;not null;default:CURRENT_TIMESTAMP" json:"update_time"`
	IsDeleted  int32      `gorm:"column:is_deleted;type:tinyint(4);not null" json:"is_deleted"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
